Change project to Django ORM only
runtimerevolution/labs pull request #145
Opened 2024-11-15 15:24 UTC by jfrverdasca

## What this PR change:

* Now project uses only Django ORM
* SQLAlchemy related code removed
* SQLAlchemy and it's dependencies removed
* Changed all SQLAlchemy related queries to Django queries ensuring the same results
* Test fix

## Reviewers:

- [ ] @kenvontucky

## Issues:

* #144 

## Print screens showing the changes:

NA

2024-11-15 16:23 UTC, kenvontucky requested changes

2024-11-15 16:23 UTC, kenvontucky commented on pyproject.toml
> +pytest-postgresql = "^6.0.0"
this should be in dev dependencies

2024-11-15 16:42 UTC, kenvontucky approved these changes

2024-11-18 09:19 UTC, JdFSilva approved these changes

2024-11-18 09:19 UTC, JdFSilva commented on labs/api/codemonkey_endpoints.py
> +    return await sync_to_async(get_llm_response_task, thread_sensitive=True)(prepared_context=get_llm_reponse.context)
why do we need `sync_to_async` and `thread_sensitive` ?

2024-11-18 09:19 UTC, JdFSilva commented on .github/workflows/ci_cd.yml
> -      - name: Create Tables
should also remove `TEST_ENVIRONMENT` from the `env` at the start of this file

2024-11-18 09:19 UTC, JdFSilva commented on labs/embeddings/base.py
>      def embed(self, prompt, *args, **kwargs) -> Embeddings:
you should call this file `embedder.py` since that's the only thing that this file has

2024-11-19 14:56 UTC, merged