Analysis starcoder2 + nomic
runtimerevolution/labs pull request #154
Opened 2024-11-26 15:20 UTC by JdFSilva

Fix `embeddins` and `embeedings` typos
Add Starcoder2-instruct + nomic analysis
Update readme

Closes #131

2024-11-26 15:57 UTC, jfrverdasca commented on notebooks/sample.ipynb
Maybe you should remove the outputs of this jupyter

2024-11-26 15:57 UTC, jfrverdasca commented on notebooks/starcoder2+nomic.ipynb
Maybe you should remove the outputs of this jupyter

2024-11-27 11:15 UTC, jfrverdasca requested changes

2024-11-27 11:15 UTC, jfrverdasca commented on README.md
> +1. `export LOCAL_LLM=True`
This is not required anymore

2024-11-27 11:19 UTC, kenvontucky approved these changes

2024-11-27 11:20 UTC, jfrverdasca approved these changes

2024-11-28 11:08 UTC, merged