Project refactor
runtimerevolution/labs pull request #161
Opened 2024-12-05 11:47 UTC by jfrverdasca

## What this PR change:

* Refactor of root llm.py file
* Refactor of root repo.py file
* Refactor of root run.py file
* Refactor of tasks
* litellm_service package refactor
* Redis now use variables to avoid key names errors
* Little bug fix

## Reviewers:

- @kenvontucky 
- @JdFSilva 

## Issues:

* #152 

## Print screens showing the changes:

NA

2024-12-06 17:08 UTC, JdFSilva commented on labs/tests/test_llm.py
> +        # it should pass without raise any excption
nit: can remove this comment

2024-12-06 17:08 UTC, JdFSilva commented on labs/tasks/redis_client.py
> +        name = variable.value if isinstance(variable, RedisVariables) else variable
can't we just type the variable as `RedisVariables`? why do we need it to be able to support strings?

2024-12-06 17:08 UTC, JdFSilva commented on labs/tasks/repository.py
> +    return variables
why do we need `as_namespace`?

2024-12-06 17:08 UTC, JdFSilva commented on labs/tasks/repository.py
> +    for step in pull_request.steps:
nit: `pull_request` should be renamed to whatever you named it on `response_parser.py`

2024-12-09 10:32 UTC, kenvontucky requested changes

2024-12-09 16:35 UTC, jfrverdasca commented on labs/tasks/run.py
> +        if not os.path.exists(kwargs[RedisVariables.REPOSITORY_PATH.value]):
It cannot because in run_on_repository (git repository) don't have it

2024-12-09 16:37 UTC, jfrverdasca commented on labs/tasks/checks.py
> +        raise ValidationError("JSON response from LLM not match the expected format.")
What is your sugestion? ValidationError and PydanticValidationError are not the same error

2024-12-10 11:07 UTC, JdFSilva approved these changes

2024-12-10 11:28 UTC, kenvontucky approved these changes

2024-12-10 12:26 UTC, merged